### ISSUE TITLE
Discussion about running data in tests

### ISSUE THREAD

**Issue by crazyshot** [ka8725/migration_data#25]
Usually, if you need some minimal data in new table, you'll both add this data in the migration, so that it will be on production, but also add it in seeds/fixtures, so that tests will have it.
In this case running these seeds right after migration also added it, will either create invalid data duplication, or fail on duplicate key constraint.

I suggest to add configuration, that will allow to not run #data / #rollback methods in test env. Yes, it removes the possibility to test the data migration with the method described in this gem's docs, but if you write exactly same data code in seeds, or find some way to just call corresponding seed from within migration, it will still work, and test that rely on this data will test that it's there.

**Comment by ka8725** [comment]
You can solve your issue in the following way:

1. Define some a class with public methods that will populate the piece of data that you have duplicated in migrations and seeds. For example, `SeedData#populate_users`

2. In the migration just call this `SeedData#populate_users`. Probably, you will have to `require` the seeds file in such kind of migrations.

So that we have an easy solution of your problem. And that's why I'm against the idea that there should be some functionality that complicates things and breaks ideology of this gem.

**Comment by crazyshot** [comment]
It doesn't fix the issue, as migration#data will call SeedData#populate_users and populate the table, and then seeds will load as part of test's setup and then duplicate key exception will happen.
So either all seeds should load with "insert ignore" or migration#data shouldn't run on tests. Second makes more sense.

**Comment by ka8725** [comment]
You can use `RAILS_ENV=test rake db:schema:load` and it will prevent the execution of migrations in test env.

**Comment by crazyshot** [comment]
It will, but only if all migrations are written in schema.rb.
I'm talking about the setup when you don't dump your schema.rb on dev, but only on production, after deploy. It's not the common approach, but I believe it's much more stable approach.

**Comment by ka8725** [comment]
Your arguments look reasonable. Would you mind to make a patch and a pull
request?

**Comment by crazyshot** [comment]
Sure. I hope I'll get to that next month.

**Comment by crazyshot** [comment]
https://github.com/ka8725/migration_data/pull/27

**Comment by ka8725** [comment]
This functionality has been just released, thank you @crazyshot for your significant contribution here.
